name: Patch new API (only when new tag is created)
on:
  push:
  workflow_dispatch:

jobs:
  build-php:
    name: Prepare PHP
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.7]

    steps:
      - uses: actions/checkout@v2 #needed for build.sh
      - name: Check for PHP build cache
        id: php-build-cache
        uses: actions/cache@v2
        with:
          path: "./bin"
          key: "php-build-generic-${{ matrix.php }}-${{ hashFiles('./tests/gh-actions/build.sh') }}"

      - name: Compile PHP
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: chmod +x ./tests/gh-actions/build.sh && ./tests/gh-actions/build.sh "${{ matrix.php }}"

  artifacts:
    name: Preprocessor tests
    needs: build-php
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.7]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Restore PHP build cache
        id: php-build-cache
        uses: actions/cache@v2
        with:
          path: "./bin"
          key: "php-build-generic-${{ matrix.php }}-${{ hashFiles('./tests/gh-actions/build.sh') }}"

      - name: Kill build on PHP build cache miss (should never happen)
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: Install cached PHP's dependencies
        if: steps.php-build-cache.outputs.cache-hit == 'true'
        run: ./tests/gh-actions/install-dependencies.sh

      - name: Prefix PHP to PATH
        run: echo "$(pwd)/bin/php7/bin" >> $GITHUB_PATH

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Restore Composer package cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ matrix.php }}-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v2-cache-
      - name: Install Composer dependencies
        run: php composer.phar install --no-dev --prefer-dist --no-interaction

      - name: Run API bump script
        env: 
          GHTOKEN: ${{ secrets.GHTOKEN }}
        run: chmod +x ./build/api-bump.sh && ./build/api-bump.sh
        
     

