name: CI tests

on:
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Compile PHP
        run: |
          sudo apt update && sudo apt install -y re2c libtool libtool-bin
          march=x86-64 ./build/php/compile.sh -j8

      - name: Prefix PHP to PATH
        run: echo "$(pwd)/bin/php7/bin" >> $GITHUB_PATH

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Restore Composer package cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer/cache/files
            ~/.composer/cache/vcs
          key: composer-cache

      - name: Install Composer dependencies
        run: php composer.phar install --prefer-dist --no-interaction

      - name: Fund Composer dependencies
        run: php composer.phar fund
      
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php --fail-on-warning tests/phpunit
        
      - name: Run integration tests
        run: ./tests/travis.sh -t4
